apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: airbnb-lab
  labels:
    app: kafka-producer
    service: airbnb-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kafka-producer
        service: airbnb-kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: 868812196149.dkr.ecr.us-east-1.amazonaws.com/airbnb/backend:lab2
        imagePullPolicy: IfNotPresent
        command: ["node", "src/kafka/producer-service.js"]
        ports:
        - containerPort: 5001
          name: http
        envFrom:
        - configMapRef:
            name: kafka-producer-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: airbnb-lab
  labels:
    app: kafka-producer
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: kafka-producer

